### ISSUE TITLE
Bug when player is in combat

### ISSUE THREAD

**Issue by durajg01** [elBukkit/PreciousStones#100]
Hello, 
My problem is when the player is in combat
doors, wickets etc. can be used

Combat Plugin : ✦ DeluxeCombat ✦ | Ultimate powerful combat resource for every server 
I present the error in the video below

https://www.youtube.com/watch?v=bxOQyrdtAz0

**Comment by xtomyserrax** [comment]
Couldnt that be related with the combat plugin itself? Have you tried contacting with the author of that plugin? Have you tried with another combat plugin?

I might do some testing with CombatLogX or another free combat plugin, but if it works fine when players are not in combat then it might be related with the combat plugin

**Comment by durajg01** [comment]
I have not contacted anyone, only reported to me right away.
I can check with CombatLog and let you know about the effect.

**Comment by xtomyserrax** [comment]
Hey were you able to do some testing with another combat plugin?

**Comment by durajg01** [comment]
Hi, by uploading the CombatLogX plug without setting it, everything works beautifully

**Comment by xtomyserrax** [comment]
Thanks for the info! Try reaching with the dev as he might be doing something with PlayerInteractEvent
