### ISSUE TITLE
A new Dynmap + PreciousStones plugin

### ISSUE THREAD

**Issue by FireController1847** [elBukkit/PreciousStones#109]
Hi there! This isn't really an issue, nor is this honestly the right place for this, but I was wondering if you wanted to possibly mention the re-creation of the classic Dynmap-PreciousStones plugin. I have re-created the plugin from the ground up and it is available here: https://github.com/FireController1847/DynmapPS

If not I totally understand, I just wanted to put this issue here so that people looking for an updated version of Dynmap-PreciousStones can find one! :)

**Comment by xtomyserrax** [comment]
Hey!! Totally, thank you for doing this, Ill put the link on the wiki and readme so you could get some traffic.

You could add that plugin to spigot too!

Edit: I just added it to the main page of this repo. Sadly I cant add it in the wiki page. Maybe someday we will migrate it to this repo (its still in marcelomason's github)

**Comment by FireController1847** [comment]
Awesome, thank you tons! The Spigot link should be in the Readme of the GitHub :)
