### ISSUE TITLE
Running allowall with a SimpleClans Clan Crashes the Server

### ISSUE THREAD

**Issue by FireController1847** [elBukkit/PreciousStones#114]
Currently investigating, but so far I can reproduce 100%:

1. Ensure MySQL is enabled (untested with SQLite)
2. Run `/ps allowall c:fakeclan` or even use a real clan, what matters it that its "c:<clanname>"
3. Observe as it takes an extremely long time to allowall, causing the server thread to freeze

Hard to notice with < 25 fields. Place more than 25 and it's obvious it is taking far too long. I am looking into this and planning on fixing it

**Comment by durajg01** [comment]
I would like to add that it was present for me when adding or removing from all plots :D

**Comment by xtomyserrax** [comment]
> I would like to add that it was present for me when adding or removing from all plots :D

@xGlenor Could you please confirm if this jar fixes the issue for you? https://github.com/elBukkit/PreciousStones/pull/115#issuecomment-796486110

**Comment by durajg01** [comment]
I'll try, but I promise nothing. Our servers flew to heaven due to a fire at OVH, So we're in the rebuilding phase, I'll try to check it out, but it will take a while.

I am using google translate so there may be errors :D
