### ISSUE TITLE
automatic removal of plots after the player's inactivity

### ISSUE THREAD

**Issue by ghost** [elBukkit/PreciousStones#120]
Hi! How to do so that the plots that are placed will automatically delete themselves after 31 days of not entering the server.

So some player places a plot, and does not enter the server for 31 days, then all his plots are deleted automatically after 31 days of being offline

**Comment by durajg01** [comment]
It seems to me that you mean this option.
The section is probably at the bottom of the file
```
cleanup:
  player-inactivity-purge-days: 30
  purge-banned-players: true
```
