### ISSUE TITLE
Glow Item Frame isnt protected

### ISSUE THREAD

**Issue by franxyk** [elBukkit/PreciousStones#124]
In sv 1.17 , drop on use glow item frame, no protecc.

**Comment by durajg01** [comment]
Have you tried to add glow_item_frame an item to the "prevent-use" list?

**Comment by franxyk** [comment]
> 
> 
> Have you tried to add glow_item_frame an item to the "prevent-use" list?

I already tried and it doesn't work.

**Comment by durajg01** [comment]
I created a Pull request correcting this error.

**Comment by xtomyserrax** [comment]
Thanks so much @xGlenor for the PR and thanks @franxyk for the bug report. If you guys find any other bug related to 1.17 please let us know!

**Comment by franxyk** [comment]
Hi there, I just tried the latest build and the problem keeps happening

**Comment by xtomyserrax** [comment]
@franxyk version 1.17.1.2 released. Please let us know if the issue is now fixed!
