### ISSUE TITLE
When will 1.18 going to be supported?

### ISSUE THREAD

**Issue by SamGamerYT** [elBukkit/PreciousStones#129]
is 1.18 coming out and .dbs to SQL converter?

**Comment by xtomyserrax** [comment]
Hey! This new version has just been released. I sadly dont have time to make updates but anyone is allowed to help with PRs. We will also wait for @NathanWolf to create a new branch for this new update!

**Comment by NathanWolf** [comment]
PreciousStones generally does not need updates for new server versions.

Have you tried it, @SamGamerYT ?

**Comment by NathanWolf** [comment]
And @xtomyserrax we never made a 1.17 branch ... I think we should get away from any processes that require changes just for versioning purposes, considering this project is (kinda?) dead.

**Comment by SamGamerYT** [comment]
> And @xtomyserrax we never made a 1.17 branch ... I think we should get away from any processes that require changes just for versioning purposes, considering this project is (kinda?) dead.

I would disagree regarding dead part, The only reason not many people know about this plugin is that it's not on Spigot, if you post it there I can ensure you a lot more people will be downloading it. - Main thing is that I wanted to go to MySQL database but I can't due to no converter hence why was wondering if it was possible.

**Comment by xtomyserrax** [comment]
> And @xtomyserrax we never made a 1.17 branch ... I think we should get away from any processes that require changes just for versioning purposes, considering this project is (kinda?) dead.

We always use master for current version. When 1.17 got released you created a 1.16 branch and started to use 1.17 in master

I know some big servers keep using this plugin but yeah, I dont have time, Nathan doesnt either and we dont have much PR helpers sadly

**Comment by NathanWolf** [comment]
> I would disagree regarding dead part,

To be clear, I meant it was dead from a development perspective. The main dev left years ago, we've been keeping it updated but don't really have the time.

Fortunately, it doesn't really need updating.

> We always use master for current version. When 1.17 got released you created a 1.16 branch and started to use 1.17 in master

Yeah .. but I guess I'm wondering why we keep doing that. I don't think it's really necessary, there are no 1.17-specific changes in master that I can see, and I don't expect we'll need any 1.18-specific changes either.

I have tested PS (minimally) on 1.18, so far no issues. Let me know if you run into anything.
