### ISSUE TITLE
Prevent using enderpearls

### ISSUE THREAD

**Issue by Axer22** [elBukkit/PreciousStones#13]
My suggestion is to add flag which can prevent from using enderpearls on field without disabling teleporting (prevent-teleport).

**Comment by xtomyserrax** [comment]
Could be named prevent-teleport-enderpearl (?

**Comment by xtomyserrax** [comment]
Hey, after some research I did, there is a flag called no-projectile-throw, which will basicly prevent players non alllowed in your field from throwing projectiles.

This though doesnt prevent it if the enderpearl was thrown outside your field, I will add a check to prevent that! Thanks :D
