### ISSUE TITLE
One more question about inactivity

### ISSUE THREAD

**Issue by Axer22** [elBukkit/PreciousStones#19]
> Hey according to the wiki:
> 
> > player-inactivity-purge-days - how many days of inactivity a player has to have before all the pstones he owns become unprotected
> 
> So yeah, I think that it will purge fields of an owner, it wont care of members as far as I know.
> 
> https://github.com/marcelo-mason/PreciousStones/wiki/Configuration
> 
_Originally posted by @xtomyserrax in https://github.com/elBukkit/PreciousStones/issues/17#issuecomment-626095090_

Inactivity means being on the server or placing/destroying blocks on the field?

**Comment by xtomyserrax** [comment]
Inactivity means the last time you joined the server, so if you join, then your "last-seen" status updates

**Comment by Axer22** [comment]
Thanks for answer.
