### ISSUE TITLE
Issue with sweet berries

### ISSUE THREAD

**Issue by Axer22** [elBukkit/PreciousStones#4]
Other players than field owner can harvest sweet berries.

**Comment by xtomyserrax** [comment]
Hey! This bug will be fixed in next version. A quick fix? Just add sweet_berry_bush to the prevent-use flag list!

I also found that players can use bone_meal in protected lands, will also fix that!

Thanks for the report!

**Comment by Axer22** [comment]
Thanks for help, I'll use it.

**Comment by xtomyserrax** [comment]
Bug fixed here: http://jenkins.elmakers.com/job/PreciousStones/33/net.sacredlabyrinth.Phaed$PreciousStones/

Thanks for the report!
