### ISSUE TITLE
Visualize Multiple Fields at Once

### ISSUE THREAD

**Issue by FireController1847** [elBukkit/PreciousStones#47]
Hey there! First off, I want to say: thank you, thank you thank you thank you for continuing this plugin and keeping it updated! I cannot show enough gratitude. I appreciate it so much.

I was thinking of visualizations recently and noticed a massive limitation in their functionality. You cannot visualize multiple fields at once. Why? This is a massive limitation! The ability to visualize multiple fields at once would allow players to get a better understanding of the total area is protected. In terms of implementation, I was thinking two things. One, allow running /ps visualize more than once, and as you walk around you can visualize multiple fields. Two, add an argument to /ps visualize for <radius>, which will visualize all of the fields in a radius.

So, if you're up for the challenge and you want to do it, then I would totally support you in your ventures!

Thanks again :)

**Comment by xtomyserrax** [comment]
Hey, this is already supported! Have you tried /ps visualize radius ? At least that worked for me, let me know!

And thank you for your words! Bug reports are really useful so let us know!

**Comment by FireController1847** [comment]
Hi there! Sorry for not responding as I totally forgot. Turns out I must have just been using too low of values, because you are right it does work! Haha.... Thank you :)

However, is there a limit to the radius? It appears to work sometimes, and other times it doesn't at all. Do the fields have to be connecting?

Also, I still think it'd be really nice to have a feature where you can run /ps visualize again in another field and instead of it complaining about a visualization already taking place, it'll just visualize another one :)

**Comment by xtomyserrax** [comment]
Hey, yeah there is a radius limit that you can change in the config.yml file! About if they must be connected or not, I think they need but Im not sure.

About your last suggestion, if someone is willing to add it yeah it could be a cool addition, but maybe it was made like that to prevent lag or issues, not sure
