### ISSUE TITLE
Allowed players can delete a field

### ISSUE THREAD

**Issue by xtomyserrax** [elBukkit/PreciousStones#52]
I have a cuboid (my plot) and i add my friend to my plot (ps allow nickname) and my friend can delete my field

**Comment by xtomyserrax** [comment]
They can use /ps take even though it has allowed-can-break flag disabled

**Comment by ikilltheundead** [comment]
Possible fix: [here](https://github.com/ikilltheundead/PreciousStones/commit/db190b4c97dafcd01850fd22da0ff4eb605d5096) However I am unable to test or verify that it works. Not a good fix as the owner of a field is a string, instead of a player object, though this might be done for a good reason.

**Comment by xtomyserrax** [comment]
The thing here is that we are not allowing a player as a guest, so the system gives co-owner permissions. I think the best alternative is to revamp the allow command by adding a new string, so you can define which type of permission group you would like to give to the new member.

Also in that command, instead of looking if player is owner, might be useful to check this flag: "allowed-can-break"

This report relates with #28
