### ISSUE TITLE
New version problems

### ISSUE THREAD

**Issue by FallenEmo** [elBukkit/PreciousStones#55]
New doors does not work as you can open them without permission: https://www.youtube.com/watch?v=ZyDZ7isb1TU 

/ps allow doesn't work at all: https://www.youtube.com/watch?v=wfvAyPwtZB0

**Comment by xtomyserrax** [comment]
About /ps allow, the command has been revamped. Please delete the language file and let the plugin generate a new one so you will see the correct message! The new usage is /ps allow player guest/coowner

About doors, which version of the plugin are you using? Have you added the flag prevent-use-doors to the field?

**Comment by FallenEmo** [comment]
I am using the latest version :// And Yes I did add that flag

**Comment by xtomyserrax** [comment]
Try checking your console log because I just tested it and it works perfectly for me. Check if the field has the flag assigned

**Comment by FallenEmo** [comment]
What would be the flag for the new blocks?

**Comment by xtomyserrax** [comment]
Its the same flag: prevent-use-doors

If you are using latest PreciousStones version then it works. Check your field info by clicking it with a pickaxe

**Comment by FallenEmo** [comment]
I reinstalled the whole thing. Still not working for me.

**Comment by xtomyserrax** [comment]
Please send me your config file and also a picture of the field information (when you right click the block with a pickaxe)

**Comment by FallenEmo** [comment]
The config is the one that is generated, so the default config. I used the City Protection so I guess that one should of been protecting the doors,

**Comment by xtomyserrax** [comment]
Hey that is why... 
If you check the config file, City Protection doesnt have the prevent-use-doors flag, but City Plot does
