### ISSUE TITLE
Flow bug

### ISSUE THREAD

**Issue by FallenEmo** [elBukkit/PreciousStones#56]
Hi, Idk if this is bug but if someone goes to the edge of the protection and goes high it can place lava which can flow into the protection. People made towers with this bug.

Yes I do have "prevent-flow: true" 

I do use the latest version

**Comment by xtomyserrax** [comment]
Could you please show some screenshots or a video? It would help a lot! Thanks

**Comment by FallenEmo** [comment]
https://www.youtube.com/watch?v=L3aw4kCmWso

No problem :)

**Comment by FallenEmo** [comment]
Is it ok?

**Comment by xtomyserrax** [comment]
Yeah thanks for the video, Ill investigate the issue

**Comment by FallenEmo** [comment]
So? Have you investigate it?

**Comment by xtomyserrax** [comment]
I already found the issue, its here: https://github.com/elBukkit/PreciousStones/blob/80085fc042458fd1ccbdc131774e63e8febd44d5/src/main/java/net/sacredlabyrinth/Phaed/PreciousStones/listeners/PSPlayerListener.java#L1276

Next version will have it fixed. Thanks for the report!
