### ISSUE TITLE
Support for "Clans" plugin?

### ISSUE THREAD

**Issue by FireController1847** [elBukkit/PreciousStones#58]
https://www.spigotmc.org/resources/clans-clan-system-1-7-1-16.22304/

I know it supports the old SimpleClans plugin, but I figured that if you wanted to, it'd be nice to support this one as it appears to also be a major mainstream clans plugin.

**Comment by xtomyserrax** [comment]
Hey, SimpleClans is a really active plugin and its having amazing updates! I wont add any new hooks, but if the author of that plugin wants to hook with PS he is free (or anyone) to make a PR or use our API!

Thanks for the suggestion though!
