### ISSUE TITLE
Limit issue

### ISSUE THREAD

**Issue by Marcuri02** [elBukkit/PreciousStones#61]
Hello, I am using the latest version updated here on Github. I noticed in a post that permissions for limits have changed, but i don’t know where can I see the new permission for limits of fields. Thanks.

**Comment by xtomyserrax** [comment]
As far as I know @ikilltheundead added information about it here: https://github.com/marcelo-mason/PreciousStones/wiki/Limits

If its still not enough, maybe #46 could help os you could tell him what is not working so he could improve the explanation on the wiki page.

Thanks!

**Comment by xtomyserrax** [comment]
Could you solve the issue @Marcuri02 ?

**Comment by Marcuri02** [comment]
Yes, solved! Thanks.
