### ISSUE TITLE
Bug placing protections

### ISSUE THREAD

**Issue by FallenEmo** [elBukkit/PreciousStones#62]
So basically if you allow someone into your protection then the person can place another protection to yours

Video: https://www.youtube.com/watch?v=2RZfq40PRmo

**Comment by xtomyserrax** [comment]
Woow thanks for the video, it definitely shouldnt allow you to place fields if you are a guest. I guess that if you are a coowner it should let you, right?

**Comment by FallenEmo** [comment]
Yup, you're right. Now I will test your newest version

**Comment by FallenEmo** [comment]
Now, I  have tested the latest one, the bug with the protection over another one, works

**Comment by xtomyserrax** [comment]
Fixed, thank you!
