### ISSUE TITLE
Prevent using sweet berries

### ISSUE THREAD

**Issue by Axer22** [elBukkit/PreciousStones#68]
When someone hold right mouse button on sweet berries on field (they doesn't added), they can collect berries. "minecraft:sweet_berry_bush" is added for "prevent-use:" flag.

**Comment by xtomyserrax** [comment]
Do you have protect-crops flag? It works fine for me with that flag

**Comment by xtomyserrax** [comment]
Was this fixed? Im closing the issue as I didnt get an answer
