### ISSUE TITLE
Other players remove members

### ISSUE THREAD

**Issue by devv4646456** [elBukkit/PreciousStones#70]
Hi. I have a problem and I don't know how to solve it. The player who was added to the plot can add others. How can you block it so that the owner can add but the person added no longer.
Sorry about my English

**Comment by xtomyserrax** [comment]
Hey, did your player add others as guests or coowners? Guests cant add new players.

Also, what version of PreciousStones do you have? Please type /version PreciousStones and let me know. Thanks!

**Comment by devv4646456** [comment]
plugin: 1.15.2.5  
Server Tuinity 1.15.2

**Comment by devv4646456** [comment]
The player using /ps allow
Players have the following privileges 
preciousstones.benefit.*
preciousstones.whitelist.*
A player added to a plot can remove others and add and change flags

I checked carefully. A guy can add and remove if you look at the main block

**Comment by xtomyserrax** [comment]
Heeey, yeah, that was a bug which was fixed but sadly it was fixed only for 1.16 versions so you will need to update your server to use this new version #62 #63
