### ISSUE TITLE
Problem with limit plots

### ISSUE THREAD

**Issue by devv4646456** [elBukkit/PreciousStones#76]
I have a problem with the configuration and I'm starting to get nervous because I don't know how to do it.
I have three different blocks filed.
 I would like to set up so that the player can only bet one of them and not one of every kind.
So that the player can place one block of all types only

My limits plots:
  limits: (block 1)
  - 1
  - 0
  - 0

  limits: (2)
  - 0
  - 1
  - 0

  
  limits: (3)
  - 0
  - 0
  - 1

**Comment by devv4646456** [comment]
Will someone help?

**Comment by xtomyserrax** [comment]
Hey sorry, Im not really familiar with this feature so I would need to check it before answering (it might be bugged).

If anyone knows about it please feel free to help. Thanks!
