### ISSUE TITLE
Flower pot use

### ISSUE THREAD

**Issue by Axer22** [elBukkit/PreciousStones#81]
Flowers planted in a flower pot can be picked up by players not allowed to the field. I tried adding "prevent-use: minecraft:flower_pot" flag but it isn't working.

**Comment by xtomyserrax** [comment]
Hey, have you tried this materials? https://github.com/elBukkit/PreciousStones/blob/acb41652ec95a1b3eb2596fbd650cac7333ff444/src/main/resources/config.yml#L68

The default config file actually has them and in my case, players cant take out flowers in flower pots.

Let me know, thanks!
