### ISSUE TITLE
Prevent flags toggleable/protection only when inside?

### ISSUE THREAD

**Issue by jamesol1** [elBukkit/PreciousStones#82]
Hey i have a few questions if thats ok.
- Is there flag/s that would make it so a protection field will only work if someone is inside the claim or offline? 
- EDIT: there isn't an option to add this WG flag  'Movecraft-move' to the protection fields any chance? 

Thanks! Its an amazing plugin!

**Comment by xtomyserrax** [comment]
Hey as far as I know for the first question, there isnt a flag that can actually do that.

I dont know what that is so if you want to send me info I can let you know if the plugin has that option. If it doesnt, any dev is free to make a PR if it adds cool content.

Thanks!

**Comment by jamesol1** [comment]
> Hey as far as I know for the first question, there isnt a flag that can actually do that.
> 
> I dont know what that is so if you want to send me info I can let you know if the plugin has that option. If it doesnt, any dev is free to make a PR if it adds cool content.
> 
> Thanks!

The second thing i mentioned is a custom flag which stops movecraft block vehicles from entering flagged regions. I don't know if some of the other options might alright prevent that but yh. They move in short via pasting/WE.
