### ISSUE TITLE
Precious interact bug

### ISSUE THREAD

**Issue by FallenEmo** [elBukkit/PreciousStones#89]
So in this video the guy pressing the button didn't have acces to the other player protection at all. Button and pressure plate could be pressed easly. 

https://www.youtube.com/watch?v=qNVEQcTlSwI

**Comment by xtomyserrax** [comment]
Hey, could you please show the flags of that field? Does it have the prevent-use-redstone flag?
In my test server it works perfectly, please let me know. Thanks!

**Comment by FallenEmo** [comment]
Didn't have the flag. Thank you. Just added.
