### ISSUE TITLE
PreciousStones Bug (Maybe)

### ISSUE THREAD

**Issue by FallenEmo** [elBukkit/PreciousStones#90]
So Apparently as you see on this video, I bug out if I go on the horse. I don't really know if there is any flag that has to do with this or not

https://www.youtube.com/watch?v=fbakSyUFNQI

**Comment by xtomyserrax** [comment]
Hey, I think prevent-entity-interact flag prevents that! Please let me know if that fixes the issue.

I can try checking another day though but Im almost sure that was the flag. Its not in the wiki though so Ill add it

EDIT: yes apparently I thought it was a bug too until I found that flag: https://github.com/elBukkit/PreciousStones/issues/42

  ?prevent-vehicle-enter: true
  ?prevent-vehicle-exit: true

Im not sure if horses are considered as vehicles. Ill test as soon as I can so I can confirm this, but I know that a flag was able to prevent players from using horses.

**Comment by FallenEmo** [comment]
I mean I was trying to do something with that flag but I thought that is not only the horses and might break something

**Comment by xtomyserrax** [comment]
Hey with prevent-entity-interact you will prevent players from interacting with any type of entity. So for example, they wont be able to use a leash to get animals out of your field.
Did this fix your issue?

**Comment by FallenEmo** [comment]
I mean it fixed, but does it break anything else?

**Comment by xtomyserrax** [comment]
No, it just prevents players from interacting with entities. So they cant breed animals so they reproduce, they can put leashes on horses, etc.

**Comment by FallenEmo** [comment]
Nooo, I mean I did try to disable these by setting it false, so they didn't bug anymore. Apart from taking the horses, does it do anything else?

  prevent-vehicle-enter: false
  prevent-vehicle-exit: false

**Comment by FallenEmo** [comment]
Also is there a flag that can make player not to interact with the lead. Only the lead and not the entity?

**Comment by xtomyserrax** [comment]
prevent-vehicle-enter: false
prevent-vehicle-exit: false

They both prevent entering and leaving a vehicle. For example a boat, if those flags are true, you cant enter a boat or exit one on a field you are not allowed to.

About interacting only with a lead I should investigate it. Im not sure if prevent-use is able to do that, I think it doesnt

**Comment by FallenEmo** [comment]
The thing is for me they can enter but they bug. And they have to kill themselves to be able to exit from there. So what I was thinking about to do, is to disable vehicle enter and try to put a flag that will deny other players to take the lead away from the horses so they won't be able to steal them
